[package]
name = "rustrix"
license = "MIT"
version = "0.1.0"
edition = "2021"
description = "Supportsc macro and basic operations for matrix."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
